### Aufgabe 1
Es seien p1,...,p15 Punkte im R2 mit den folgenden paarweisen Abständen:

In [1]:
import numpy as np
import pandas as pd

# Gegebene paarweise Abstände als Matrix
distances = np.array([
    [0.0, 2.8, 1.6, 7.2, 6.0, 8.1, 6.8, 3.0, 6.3, 4.6, 3.8, 7.9, 7.3, 10.1, 7.9],
    [2.8, 0.0, 1.6, 5.0, 5.7, 8.5, 4.5, 1.8, 6.1, 2.7, 3.8, 5.5, 5.0, 9.9, 7.9],
    [1.6, 1.6, 0.0, 6.5, 6.4, 8.9, 6.0, 1.5, 6.7, 4.0, 2.8, 7.1, 6.5, 10.6, 8.5],
    [7.2, 5.0, 6.5, 0.0, 4.3, 7.1, 0.7, 6.7, 4.7, 2.5, 8.7, 1.1, 0.5, 7.2, 6.0],
    [6.0, 5.7, 6.4, 4.3, 0.0, 3.0, 4.6, 7.4, 0.5, 3.6, 9.2, 5.4, 4.7, 4.2, 2.2],
    [8.1, 8.5, 8.9, 7.1, 3.0, 0.0, 7.5, 10.1, 2.5, 6.7, 11.7, 8.1, 7.6, 2.5, 1.1],
    [6.8, 4.5, 6.0, 0.7, 4.6, 7.5, 0.0, 6.1, 5.1, 2.2, 8.1, 1.1, 0.5, 7.8, 6.5],
    [3.0, 1.8, 1.5, 6.7, 7.4, 10.1, 6.1, 0.0, 7.8, 4.5, 2.1, 7.0, 6.6, 11.7, 9.6],
    [6.3, 6.1, 6.7, 4.7, 0.5, 2.5, 5.1, 7.8, 0.0, 4.1, 9.6, 5.9, 5.2, 3.9, 1.8],
    [4.6, 2.7, 4.0, 2.5, 3.6, 6.7, 2.2, 4.5, 4.1, 0.0, 6.5, 3.4, 2.7, 7.6, 5.9],
    [3.8, 3.8, 2.8, 8.7, 9.2, 11.7, 8.1, 2.1, 9.6, 6.5, 0.0, 9.1, 8.6, 13.5, 11.3],
    [7.9, 5.5, 7.1, 1.1, 5.4, 8.1, 1.1, 7.0, 5.9, 3.4, 9.1, 0.0, 0.7, 8.1, 7.1],
    [7.3, 5.0, 6.5, 0.5, 4.7, 7.6, 0.5, 6.6, 5.2, 2.7, 8.6, 0.7, 0.0, 7.6, 6.5],
    [10.1, 9.9, 10.6, 7.2, 4.2, 2.5, 7.8, 11.7, 3.9, 7.6, 13.5, 8.1, 7.6, 0.0, 2.2],
    [7.9, 7.9, 8.5, 6.0, 2.2, 1.1, 6.5, 9.6, 1.8, 5.9, 11.3, 7.1, 6.5, 2.2, 0.0]
])

# Anzahl der Punkte
n_points = distances.shape[0]

(a) Bestimmen sie die Kerndistanzen aller Punkte für minPts=3.

In [3]:
# Kerndistanzen für minPts = 3 bestimmen
minPts = 3

# Sortiere die Abstände für jeden Punkt
sorted_distances = np.sort(distances, axis=1)

# Kerndistanz ist der minPts-1-kleinste Abstand (Index = minPts-1)
core_distances = sorted_distances[:, minPts]

core_distances

array([3. , 2.7, 1.6, 1.1, 3. , 2.5, 1.1, 2.1, 2.5, 2.7, 3.8, 1.1, 0.7,
       3.9, 2.2])

(b) Es sei $\epsilon = 2$. Bestimmen sie alle Kernobjekte.

In [5]:
# Kernobjekte bestimmen für epsilon = 2
epsilon = 2

# Zähle die Anzahl der Punkte in der epsilon-Nachbarschaft für jeden Punkt
neighbors_count = np.sum(distances <= epsilon, axis=1)

# Kernobjekte sind Punkte mit mindestens minPts Nachbarn (einschließlich des Punktes selbst)
core_objects = neighbors_count >= minPts

# Liste der Kernobjekte (True für Kernobjekt, False sonst)
core_objects


array([False,  True,  True,  True, False, False,  True,  True,  True,
       False, False,  True,  True, False,  True])

(c) Bestimmen Sie alle Rand- und Rauschobjekte.

In [6]:
# Rand- und Rauschobjekte bestimmen

# Randobjekte: Punkte in der epsilon-Nachbarschaft eines Kernobjekts, aber selbst keine Kernobjekte
is_border_object = np.any((distances <= epsilon) & core_objects, axis=1) & ~core_objects

# Rauschobjekte: Punkte, die weder Kernobjekte noch Randobjekte sind
is_noise_object = ~core_objects & ~is_border_object

# Ergebnisse
border_objects = is_border_object
noise_objects = is_noise_object

border_objects, noise_objects

(array([ True, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False]),
 array([False, False, False, False, False, False, False, False, False,
         True,  True, False, False,  True, False]))

(d) Bestimmen sie die Clusterzuordnung für $\epsilon = 2$ und minPts=3.

In [ ]:
from sklearn.cluster import DBSCAN

# DBSCAN auf den Abstandsmetriken ausführen
dbscan = DBSCAN(eps=epsilon, min_samples=minPts, metric="precomputed")
labels = dbscan.fit_predict(distances)

# Clusterzuordnungen (Rauschpunkte haben das Label -1)
labels



(e) Berechnen Sie (basierend auf der in Aufgabenteil (d) ermittelten Zuordnung)
 den Silhouettenkoeffizienten für den Punkt p9.

In [ ]:
# Clusterzugehörigkeit von p9
cluster_of_p9 = labels[8]

# Punkte im gleichen Cluster wie p9
same_cluster = (labels == cluster_of_p9)

# Punkte in anderen Clustern
other_clusters = (labels != cluster_of_p9) & (labels != -1)

# a(p9): Durchschnittliche Distanz innerhalb desselben Clusters
intra_cluster_distances = distances[8, same_cluster]  # Distanzen zu Punkten im selben Cluster
a_p9 = np.mean(intra_cluster_distances[intra_cluster_distances > 0])  # Mittelwert ohne den Punkt selbst

# b(p9): Durchschnittliche Distanz zum nächstgelegenen anderen Cluster
inter_cluster_distances = [
    np.mean(distances[8, labels == cluster]) for cluster in set(labels) if cluster != cluster_of_p9 and cluster != -1
]
b_p9 = min(inter_cluster_distances) if inter_cluster_distances else float('inf')

# Silhouettenkoeffizient berechnen
silhouette_coefficient_p9 = (b_p9 - a_p9) / max(a_p9, b_p9)
a_p9, b_p9, silhouette_coefficient_p9


### Aufgabe 2 Cluster-Repr¨ asentanten 10Punkte

Im Rahmen des Verfahrens \( k \)-Means wird ein Cluster durch sein Zentrum repräsentiert, das i. A. nicht aus der ursprünglichen Datenmenge \( D \) stammt.  
Bei \( k \)-Medoids dagegen ist der Repräsentant jedes Clusters ein Element aus \( D \).

#### Antwort

1. **Interpretierbarkeit und Verständlichkeit**
- **Erläuterung**:  
  Die Repräsentanten stammen aus der ursprünglichen Datenmenge \( D \), was sie für Menschen leichter interpretierbar macht. Solche Repräsentanten sind reale Datenpunkte und bieten konkrete Beispiele für die Eigenschaften eines Clusters.  
  Dies ist besonders nützlich, um Ergebnisse der Clusteranalyse an Stakeholder zu kommunizieren, die möglicherweise mit den technischen Aspekten nicht vertraut sind.

2. **Robustheit gegenüber Ausreißern**
- **Erläuterung**:  
  \( k \)-Medoids wählt tatsächliche Datenpunkte als Cluster-Repräsentanten, wodurch das Verfahren weniger empfindlich gegenüber Ausreißern ist. Anders als bei \( k \)-Means, wo Ausreißer die Zentren stark verschieben können, bleibt der Repräsentant bei \( k \)-Medoids stabil und repräsentiert typischerweise die Mehrheit der Daten im Cluster besser.



### Aufgabe 3 Divisives Clustern

Es sei $n \in \mathbb{N}$, $n \geq 2$.  
Zeigen Sie, dass es genau $2^{n-1} - 1$ verschiedene Möglichkeiten gibt, ein Cluster mit $n$ Elementen in zwei disjunkte nichtleere Teilcluster aufzuteilen.

#### 1. **Grundidee**:
Ein Cluster mit $n$ Elementen lässt sich in zwei disjunkte Teilcluster \( A \) und \( B \) aufteilen, wobei beide Teilcluster nicht leer sein dürfen.  
Für jede Aufteilung gibt es eine eindeutige Zuordnung jedes Elements zu entweder \( A \) oder \( B \). Dies kann durch Binärentscheidungen beschrieben werden.

---

#### 2. **Gesamtanzahl von Zuordnungen**:
- Jedes der \( n \) Elemente kann entweder in \( A \) oder \( B \) eingeordnet werden. Es gibt also insgesamt $2^n$ mögliche Zuordnungen.
- Allerdings sind Aufteilungen, bei denen \( A \) oder \( B \) leer ist, unzulässig. Das bedeutet, es bleiben $2^n - 2$ mögliche Zuordnungen übrig (wir subtrahieren die beiden Fälle, in denen \( A \) leer ist oder \( B \) leer ist).

---

#### 3. **Symmetrische Aufteilungen eliminieren**:
- Jede Aufteilung \( (A, B) \) ist symmetrisch zu \( (B, A) \). Das bedeutet, wir zählen jede Aufteilung doppelt.  
- Um dies zu korrigieren, teilen wir die Anzahl der verbleibenden Zuordnungen durch 2:
  $$
  \frac{2^n - 2}{2} = 2^{n-1} - 1
  $$

---

#### 4. **Schlussfolgerung**:
Es gibt genau $2^{n-1} - 1$ verschiedene Möglichkeiten, ein Cluster mit \( n \) Elementen in zwei disjunkte, nichtleere Teilcluster aufzuteilen.
